version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8085:8080"
    volumes:
      - /home/server2/docker_volumes/lorabs-map/web:/app
      - /home/server2/docker_volumes/lorabs-map/shared:/app/shared
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - /home/server2/docker_volumes/lorabs-map/bot:/app
      - /home/server2/docker_volumes/lorabs-map/shared:/app/shared
    environment:
      - BOT_TOKEN=8054423751:AAFfYrxvp86yTnGnlD59kJ7IHQeZSl1oRRs  # imposta anche il tuo token in locale oppure in un .env
    depends_on:
      - web
    restart: unless-stopped
